export default [
  { language: 'Arabic', symbol: 'ar', text: 'لا، شكرا' },
  { language: 'Dutch', symbol: 'nl', text: 'Nee, dank u' },
  { language: 'French', symbol: 'fr', text: 'non, merci' },
  { language: 'German', symbol: 'de', text: 'Nein danke' },
  { language: 'Italian', symbol: 'it', text: 'no grazie' },
  { language: 'Japanese', symbol: 'ja', text: 'いいえ、結構です' },
  { language: 'Russian', symbol: 'ru', text: 'нет, спасибо' },
  { language: 'Spanish', symbol: 'es', text: 'no gracias' },
  { language: 'Bengali', symbol: 'bn', text: 'না, ধন্যবাদ' },
  { language: 'Bulgarian', symbol: 'bg', text: 'не благодаря' },
  { language: 'Catalan', symbol: 'ca', text: 'no gràcies' },
  { language: 'Chinese Simplified', symbol: 'zh-cn', text: '不，谢谢' },
  { language: 'Chinese Traditional', symbol: 'zh-tw', text: '不，謝謝' },
  { language: 'Croatian', symbol: 'hr', text: 'ne hvala' },
  { language: 'Czech', symbol: 'cs', text: 'ne, děkuji' },
  { language: 'Danish', symbol: 'da', text: 'Nej tak' },
  { language: 'Esperanto', symbol: 'eo', text: 'ne dankon' },
  { language: 'Estonian', symbol: 'et', text: 'ei aitäh' },
  { language: 'Filipino', symbol: 'tl', text: 'Hindi, salamat' },
  { language: 'Finnish', symbol: 'fi', text: 'ei kiitos' },
  { language: 'Greek', symbol: 'el', text: 'όχι ευχαριστώ' },
  { language: 'Hebrew', symbol: 'iw', text: 'לא תודה' },
  { language: 'Indonesian', symbol: 'id', text: 'tidak terima kasih' },
  { language: 'Korean', symbol: 'ko', text: '아니요 괜찮습니다' },
  { language: 'Latvian', symbol: 'lv', text: 'Nē paldies' },
  { language: 'Lithuanian', symbol: 'lt', text: 'ne ačiū' },
  { language: 'Malay', symbol: 'ms', text: 'tidak, terima kasih' },
  { language: 'Malayalam', symbol: 'ml', text: 'ഇല്ല നന്ദി' },
  { language: 'Marathi', symbol: 'mr', text: 'नको, धन्यवाद' },
  { language: 'Norwegian', symbol: 'no', text: 'Nei takk' },
  { language: 'Polish', symbol: 'pl', text: 'nie, dziękuję' },
  { language: 'Portuguese', symbol: 'pt', text: 'não obrigado' },
  { language: 'Romanian', symbol: 'ro', text: 'nu, mulțumesc' },
  { language: 'Serbian', symbol: 'sr', text: 'не хвала' },
  { language: 'Slovak', symbol: 'sk', text: 'nie ďakujem' },
  { language: 'Slovenian', symbol: 'sl', text: 'ne, hvala' },
  { language: 'Swedish', symbol: 'sv', text: 'Nej tack' },
  { language: 'Tajik', symbol: 'tg', text: 'не ташаккур' },
  { language: 'Tamil', symbol: 'ta', text: 'பரவாயில்லை, நன்றி' },
  { language: 'Telugu', symbol: 'te', text: 'అక్కర్లేదు' },
  { language: 'Thai', symbol: 'th', text: 'ไม่เป็นไรขอบคุณ' },
  { language: 'Turkish', symbol: 'tr', text: 'hayır teşekkürler' },
  { language: 'Ukrainian', symbol: 'uk', text: 'ні, дякую' },
  { language: 'Urdu', symbol: 'ur', text: 'نہیں شکریہ' },
  { language: 'Vietnamese', symbol: 'vi', text: 'không cám ơn' },
  { language: 'Afrikaans', symbol: 'af', text: 'Nee dankie' },
  { language: 'Albanian', symbol: 'sq', text: 'jo faleminderit' },
  { language: 'Amharic', symbol: 'am', text: 'አይ አመሰግናለሁ' },
  { language: 'Armenian', symbol: 'hy', text: 'ոչ, շնորհակալ եմ' },
  { language: 'Azerbaijani', symbol: 'az', text: 'Xeyr, sağ olun' },
  { language: 'Basque', symbol: 'eu', text: 'ez eskerrik asko' },
  { language: 'Belarusian', symbol: 'be', text: 'не, дзякуй' },
  { language: 'Bosnian', symbol: 'bs', text: 'ne hvala' },
  { language: 'Cebuano', symbol: 'ceb', text: 'dili salamat' },
  { language: 'Chichewa', symbol: 'ny', text: 'ayi zikomo' },
  { language: 'Corsican', symbol: 'co', text: 'innò ti ringraziu' },
  { language: 'Frisian', symbol: 'fy', text: 'Nee Tankewol' },
  { language: 'Galician', symbol: 'gl', text: 'non grazas' },
  { language: 'Georgian', symbol: 'ka', text: 'არა გმადლობთ' },
  { language: 'Gujarati', symbol: 'gu', text: 'નહીં અાભાર તમારો' },
  { language: 'Haitian Creole', symbol: 'ht', text: 'Non mèsi' },
  { language: 'Hausa', symbol: 'ha', text: "a'a na gode" },
  { language: 'Hawaiian', symbol: 'haw', text: 'no mahalo' },
  { language: 'Hindi', symbol: 'hi', text: 'नहीं धन्यवाद' },
  { language: 'Hmong', symbol: 'hmn', text: 'tsis muaj ua tsaug' },
  { language: 'Hungarian', symbol: 'hu', text: 'nem, köszönöm' },
  { language: 'Icelandic', symbol: 'is', text: 'Nei takk' },
  { language: 'Igbo', symbol: 'ig', text: 'mba daalụ' },
  { language: 'Irish', symbol: 'ga', text: 'ní raibh maith agat' },
  { language: 'Javanese', symbol: 'jw', text: 'ora matur nuwun' },
  { language: 'Kannada', symbol: 'kn', text: 'ಇಲ್ಲ ಧನ್ಯವಾದಗಳು' },
  { language: 'Kazakh', symbol: 'kk', text: 'жоқ рахмет' },
  { language: 'Khmer', symbol: 'km', text: 'មិន​អី​ទេ​អរគុណ​ហើយ' },
  { language: 'Kurdish', symbol: 'ku', text: 'na spas' },
  { language: 'Kyrgyz', symbol: 'ky', text: 'жок рахмат' },
  { language: 'Lao', symbol: 'lo', text: 'ບໍ່​ຂອບ​ໃຈ' },
  { language: 'Latin', symbol: 'la', text: 'non gratias tibi aget' },
  { language: 'Luxembourgish', symbol: 'lb', text: 'nee merci' },
  { language: 'Macedonian', symbol: 'mk', text: 'не благодарам' },
  { language: 'Malagasy', symbol: 'mg', text: 'tsia misaotra' },
  { language: 'Maltese', symbol: 'mt', text: 'le grazzi' },
  { language: 'Maori', symbol: 'mi', text: 'kāo, whakawhetai' },
  { language: 'Mongolian', symbol: 'mn', text: 'үгүй ээ баярлалаа' },
  { language: 'Myanmar', symbol: 'my', text: 'မဟုတ်ဘူးကျေးဇူးတင်ပါတယ်' },
  { language: 'Nepali', symbol: 'ne', text: 'होईन, धन्यवाद' },
  { language: 'Pashto', symbol: 'ps', text: 'نه مننه' },
  { language: 'Persian', symbol: 'fa', text: 'نه ممنون' },
  { language: 'Samoan', symbol: 'sm', text: 'leai faafetai' },
  { language: 'Scots Gaelic', symbol: 'gd', text: 'gun taing' },
  { language: 'Sesotho', symbol: 'st', text: 'che, kea leboha' },
  { language: 'Shona', symbol: 'sn', text: 'kwete maita basa' },
  { language: 'Sindhi', symbol: 'sd', text: 'نه توهان جي مهرباني' },
  { language: 'Sinhala', symbol: 'si', text: 'නෑ ස්තූතියි' },
  { language: 'Somali', symbol: 'so', text: 'maya mahadsanid' },
  { language: 'Sundanese', symbol: 'su', text: 'henteu hatur nuhun' },
  { language: 'Swahili', symbol: 'sw', text: 'Hapana Asante' },
  { language: 'Uzbek', symbol: 'uz', text: "yo'q rahmat" },
  { language: 'Welsh', symbol: 'cy', text: 'Dim Diolch' },
  { language: 'Xhosa', symbol: 'xh', text: 'hayi enkosi' },
  { language: 'Yiddish', symbol: 'yi', text: 'ניין א דאנק' },
  { language: 'Yoruba', symbol: 'yo', text: 'rárá o ṣeun' },
  { language: 'Zulu', symbol: 'zu', text: 'cha ngiyabonga' },
];
