export default [
  { language: 'Arabic', symbol: 'ar', text: 'شكرا' },
  { language: 'Dutch', symbol: 'nl', text: 'dank je' },
  { language: 'French', symbol: 'fr', text: 'Merci' },
  { language: 'German', symbol: 'de', text: 'Danke' },
  { language: 'Italian', symbol: 'it', text: 'grazie' },
  { language: 'Japanese', symbol: 'ja', text: 'ありがとうございました' },
  { language: 'Russian', symbol: 'ru', text: 'благодарю вас' },
  { language: 'Spanish', symbol: 'es', text: 'gracias' },
  { language: 'Bengali', symbol: 'bn', text: 'ধন্যবাদ' },
  { language: 'Bulgarian', symbol: 'bg', text: 'Благодаря ти' },
  { language: 'Catalan', symbol: 'ca', text: 'gràcies' },
  { language: 'Chinese Simplified', symbol: 'zh-cn', text: '谢谢' },
  { language: 'Chinese Traditional', symbol: 'zh-tw', text: '謝謝' },
  { language: 'Croatian', symbol: 'hr', text: 'Hvala vam' },
  { language: 'Czech', symbol: 'cs', text: 'Děkuji' },
  { language: 'Danish', symbol: 'da', text: 'tak skal du have' },
  { language: 'Esperanto', symbol: 'eo', text: 'Dankon' },
  { language: 'Estonian', symbol: 'et', text: 'aitäh' },
  { language: 'Filipino', symbol: 'tl', text: 'Salamat' },
  { language: 'Finnish', symbol: 'fi', text: 'Kiitos' },
  { language: 'Greek', symbol: 'el', text: 'ευχαριστώ' },
  { language: 'Hebrew', symbol: 'iw', text: 'תודה' },
  { language: 'Indonesian', symbol: 'id', text: 'Terima kasih' },
  { language: 'Korean', symbol: 'ko', text: '감사합니다' },
  { language: 'Latvian', symbol: 'lv', text: 'Paldies' },
  { language: 'Lithuanian', symbol: 'lt', text: 'Ačiū' },
  { language: 'Malay', symbol: 'ms', text: 'terima kasih' },
  { language: 'Malayalam', symbol: 'ml', text: 'നന്ദി' },
  { language: 'Marathi', symbol: 'mr', text: 'धन्यवाद' },
  { language: 'Norwegian', symbol: 'no', text: 'Takk skal du ha' },
  { language: 'Polish', symbol: 'pl', text: 'Dziękuję Ci' },
  { language: 'Portuguese', symbol: 'pt', text: 'obrigado' },
  { language: 'Romanian', symbol: 'ro', text: 'mulțumesc' },
  { language: 'Serbian', symbol: 'sr', text: 'Хвала вам' },
  { language: 'Slovak', symbol: 'sk', text: 'Ďakujem' },
  { language: 'Slovenian', symbol: 'sl', text: 'Hvala vam' },
  { language: 'Swedish', symbol: 'sv', text: 'tack' },
  { language: 'Tajik', symbol: 'tg', text: 'сипос' },
  { language: 'Tamil', symbol: 'ta', text: 'நன்றி' },
  { language: 'Telugu', symbol: 'te', text: 'ధన్యవాదాలు' },
  { language: 'Thai', symbol: 'th', text: 'ขอขอบคุณ' },
  { language: 'Turkish', symbol: 'tr', text: 'teşekkür ederim' },
  { language: 'Ukrainian', symbol: 'uk', text: 'спасибі' },
  { language: 'Urdu', symbol: 'ur', text: 'آپ کا شکریہ' },
  { language: 'Vietnamese', symbol: 'vi', text: 'cảm ơn bạn' },
  { language: 'Afrikaans', symbol: 'af', text: 'Dankie' },
  { language: 'Albanian', symbol: 'sq', text: 'faleminderit' },
  { language: 'Amharic', symbol: 'am', text: 'አመሰግናለሁ' },
  { language: 'Armenian', symbol: 'hy', text: 'շնորհակալություն' },
  { language: 'Azerbaijani', symbol: 'az', text: 'çox sağ ol' },
  { language: 'Basque', symbol: 'eu', text: 'eskerrik asko' },
  { language: 'Belarusian', symbol: 'be', text: 'Дзякуй' },
  { language: 'Bosnian', symbol: 'bs', text: 'hvala ti' },
  { language: 'Cebuano', symbol: 'ceb', text: 'salamat' },
  { language: 'Chichewa', symbol: 'ny', text: 'Zikomo' },
  { language: 'Corsican', symbol: 'co', text: 'à ringrazià ti' },
  { language: 'Frisian', symbol: 'fy', text: 'Dankewol' },
  { language: 'Galician', symbol: 'gl', text: 'grazas' },
  { language: 'Georgian', symbol: 'ka', text: 'გმადლობთ' },
  { language: 'Gujarati', symbol: 'gu', text: 'આભાર' },
  { language: 'Haitian Creole', symbol: 'ht', text: 'mèsi' },
  { language: 'Hausa', symbol: 'ha', text: 'na gode' },
  { language: 'Hawaiian', symbol: 'haw', text: 'mahalo' },
  { language: 'Hindi', symbol: 'hi', text: 'धन्यवाद' },
  { language: 'Hmong', symbol: 'hmn', text: 'ua tsaug' },
  { language: 'Hungarian', symbol: 'hu', text: 'köszönöm' },
  { language: 'Icelandic', symbol: 'is', text: 'Þakka þér fyrir' },
  { language: 'Igbo', symbol: 'ig', text: 'Daalụ' },
  { language: 'Irish', symbol: 'ga', text: 'go raibh maith agat' },
  { language: 'Javanese', symbol: 'jw', text: 'matur nuwun' },
  { language: 'Kannada', symbol: 'kn', text: 'ಧನ್ಯವಾದಗಳು' },
  { language: 'Kazakh', symbol: 'kk', text: 'Рақмет сізге' },
  { language: 'Khmer', symbol: 'km', text: 'សូមអរគុណ' },
  { language: 'Kurdish', symbol: 'ku', text: 'sipas ji were' },
  { language: 'Kyrgyz', symbol: 'ky', text: 'рахмат сага' },
  { language: 'Lao', symbol: 'lo', text: 'ຂອບ​ໃຈ' },
  { language: 'Latin', symbol: 'la', text: 'gratias tibi' },
  { language: 'Luxembourgish', symbol: 'lb', text: 'Merci' },
  { language: 'Macedonian', symbol: 'mk', text: 'Ви благодарам' },
  { language: 'Malagasy', symbol: 'mg', text: 'Misaotra anao' },
  { language: 'Maltese', symbol: 'mt', text: 'Grazzi' },
  { language: 'Maori', symbol: 'mi', text: 'kia ora' },
  { language: 'Mongolian', symbol: 'mn', text: 'баярлалаа' },
  { language: 'Myanmar', symbol: 'my', text: 'ကျေးဇူးတင်ပါတယ်' },
  { language: 'Nepali', symbol: 'ne', text: 'धन्यवाद' },
  { language: 'Pashto', symbol: 'ps', text: 'له تاسو مننه' },
  { language: 'Persian', symbol: 'fa', text: 'متشکرم' },
  { language: 'Samoan', symbol: 'sm', text: 'faafetai' },
  { language: 'Scots Gaelic', symbol: 'gd', text: 'Tapadh leat' },
  { language: 'Sesotho', symbol: 'st', text: 'kea leboha' },
  { language: 'Shona', symbol: 'sn', text: 'waita hako' },
  { language: 'Sindhi', symbol: 'sd', text: 'توهان جي مهرباني' },
  { language: 'Sinhala', symbol: 'si', text: 'ඔබට ස්තුතියි' },
  { language: 'Somali', symbol: 'so', text: 'mahadsanid' },
  { language: 'Sundanese', symbol: 'su', text: 'hatur nuhun' },
  { language: 'Swahili', symbol: 'sw', text: 'Asante' },
  { language: 'Uzbek', symbol: 'uz', text: 'rahmat' },
  { language: 'Welsh', symbol: 'cy', text: 'Diolch' },
  { language: 'Xhosa', symbol: 'xh', text: 'enkosi' },
  { language: 'Yiddish', symbol: 'yi', text: 'אדאנק' },
  { language: 'Yoruba', symbol: 'yo', text: 'e dupe' },
  { language: 'Zulu', symbol: 'zu', text: 'Ngiyabonga' },
];
