export default [
  { language: 'Arabic', symbol: 'ar', text: 'لا شكرا' },
  { language: 'Dutch', symbol: 'nl', text: 'Nee bedankt' },
  { language: 'French', symbol: 'fr', text: 'Non merci' },
  { language: 'German', symbol: 'de', text: 'Nein Danke' },
  { language: 'Italian', symbol: 'it', text: 'No grazie' },
  { language: 'Japanese', symbol: 'ja', text: '結構です' },
  { language: 'Russian', symbol: 'ru', text: 'Нет, спасибо' },
  { language: 'Spanish', symbol: 'es', text: 'no, gracias' },
  { language: 'Bengali', symbol: 'bn', text: 'না ধন্যবাদ' },
  { language: 'Bulgarian', symbol: 'bg', text: 'не благодаря' },
  { language: 'Catalan', symbol: 'ca', text: 'no gràcies' },
  { language: 'Chinese Simplified', symbol: 'zh-cn', text: '不用了，谢谢' },
  { language: 'Chinese Traditional', symbol: 'zh-tw', text: '不用了，謝謝' },
  { language: 'Croatian', symbol: 'hr', text: 'ne hvala' },
  { language: 'Czech', symbol: 'cs', text: 'ne, díky' },
  { language: 'Danish', symbol: 'da', text: 'Nej tak' },
  { language: 'Esperanto', symbol: 'eo', text: 'ne, dankon' },
  { language: 'Estonian', symbol: 'et', text: 'ei aitäh' },
  { language: 'Filipino', symbol: 'tl', text: 'Salamat nalang' },
  { language: 'Finnish', symbol: 'fi', text: 'ei kiitos' },
  { language: 'Greek', symbol: 'el', text: 'όχι ευχαριστώ' },
  { language: 'Hebrew', symbol: 'iw', text: 'לא תודה' },
  { language: 'Indonesian', symbol: 'id', text: 'tidak, terima kasih' },
  { language: 'Korean', symbol: 'ko', text: '고맙지 만 사양 할게' },
  { language: 'Latvian', symbol: 'lv', text: 'Nē paldies' },
  { language: 'Lithuanian', symbol: 'lt', text: 'ne, ačiū' },
  { language: 'Malay', symbol: 'ms', text: 'tidak, Terima kasih' },
  { language: 'Malayalam', symbol: 'ml', text: 'വേണ്ട, നന്ദി' },
  { language: 'Marathi', symbol: 'mr', text: 'नको धन्यवाद' },
  { language: 'Norwegian', symbol: 'no', text: 'Nei takk' },
  { language: 'Polish', symbol: 'pl', text: 'Nie, dziękuję' },
  { language: 'Portuguese', symbol: 'pt', text: 'não, obrigado' },
  { language: 'Romanian', symbol: 'ro', text: 'nu multumesc' },
  { language: 'Serbian', symbol: 'sr', text: 'не хвала' },
  { language: 'Slovak', symbol: 'sk', text: 'nie ďakujem' },
  { language: 'Slovenian', symbol: 'sl', text: 'ne hvala' },
  { language: 'Swedish', symbol: 'sv', text: 'Nej tack' },
  { language: 'Tajik', symbol: 'tg', text: 'не ташаккур' },
  { language: 'Tamil', symbol: 'ta', text: 'நன்றி இல்லை' },
  { language: 'Telugu', symbol: 'te', text: 'ధన్యవాదాలు లేదు' },
  { language: 'Thai', symbol: 'th', text: 'ไม่เป็นไรขอบคุณ' },
  { language: 'Turkish', symbol: 'tr', text: 'hayır teşekkürler' },
  { language: 'Ukrainian', symbol: 'uk', text: 'ні, дякую' },
  { language: 'Urdu', symbol: 'ur', text: 'نہیں شکریہ' },
  { language: 'Vietnamese', symbol: 'vi', text: 'không, cám ơn' },
  { language: 'Afrikaans', symbol: 'af', text: 'Nee dankie' },
  { language: 'Albanian', symbol: 'sq', text: 'jo faleminderit' },
  { language: 'Amharic', symbol: 'am', text: 'አይ አመሰግናለሁ' },
  { language: 'Armenian', symbol: 'hy', text: 'ոչ, շնորհակալություն' },
  { language: 'Azerbaijani', symbol: 'az', text: 'Xeyr, təşəkkürlər' },
  { language: 'Basque', symbol: 'eu', text: 'ez eskerrik asko' },
  { language: 'Belarusian', symbol: 'be', text: 'не, дзякуй' },
  { language: 'Bosnian', symbol: 'bs', text: 'ne hvala' },
  { language: 'Cebuano', symbol: 'ceb', text: 'dili salamat' },
  { language: 'Chichewa', symbol: 'ny', text: 'ayi zikomo' },
  { language: 'Corsican', symbol: 'co', text: 'innò grazie' },
  { language: 'Frisian', symbol: 'fy', text: 'nee tank' },
  { language: 'Galician', symbol: 'gl', text: 'non, grazas' },
  { language: 'Georgian', symbol: 'ka', text: 'არა გმადლობთ' },
  { language: 'Gujarati', symbol: 'gu', text: 'ના આભાર' },
  { language: 'Haitian Creole', symbol: 'ht', text: 'Non mèsi' },
  { language: 'Hausa', symbol: 'ha', text: "A'a na gode" },
  { language: 'Hawaiian', symbol: 'haw', text: 'mahalo ʻole' },
  { language: 'Hindi', symbol: 'hi', text: 'जी नहीं, धन्यवाद' },
  { language: 'Hmong', symbol: 'hmn', text: 'tsis ua tsaug' },
  { language: 'Hungarian', symbol: 'hu', text: 'nem köszönöm' },
  { language: 'Icelandic', symbol: 'is', text: 'Nei takk' },
  { language: 'Igbo', symbol: 'ig', text: 'mba, daalụ' },
  { language: 'Irish', symbol: 'ga', text: 'Níl sé uaim go raibh maith agat' },
  { language: 'Javanese', symbol: 'jw', text: 'ora matur nuwun' },
  { language: 'Kannada', symbol: 'kn', text: 'ಬೇಡ ಧನ್ಯವಾದಗಳು' },
  { language: 'Kazakh', symbol: 'kk', text: 'жоқ Рақмет' },
  { language: 'Khmer', symbol: 'km', text: 'អត់អី​ទេ​អរគុណ​ហើយ' },
  { language: 'Kurdish', symbol: 'ku', text: 'na spas' },
  { language: 'Kyrgyz', symbol: 'ky', text: 'Жок, рахмат' },
  { language: 'Lao', symbol: 'lo', text: 'ບໍ່​ຂອບ​ໃຈ' },
  { language: 'Latin', symbol: 'la', text: 'non grates' },
  { language: 'Luxembourgish', symbol: 'lb', text: 'Nee Merci' },
  { language: 'Macedonian', symbol: 'mk', text: 'Не, благодарам' },
  { language: 'Malagasy', symbol: 'mg', text: 'tsia fa misaotra' },
  { language: 'Maltese', symbol: 'mt', text: 'le grazzi' },
  { language: 'Maori', symbol: 'mi', text: 'kaore he mihi' },
  { language: 'Mongolian', symbol: 'mn', text: 'үгүй ээ баярлалаа' },
  { language: 'Myanmar', symbol: 'my', text: 'ရပါတယ်ကျေးဇူးပါ' },
  { language: 'Nepali', symbol: 'ne', text: 'होईन, धन्यवाद' },
  { language: 'Pashto', symbol: 'ps', text: 'نه مننه' },
  { language: 'Persian', symbol: 'fa', text: 'نه ممنون' },
  { language: 'Samoan', symbol: 'sm', text: 'leai faafetai' },
  { language: 'Scots Gaelic', symbol: 'gd', text: 'Chan eil taing' },
  { language: 'Sesotho', symbol: 'st', text: 'Che kea leboha' },
  { language: 'Shona', symbol: 'sn', text: 'kwete ndatenda' },
  { language: 'Sindhi', symbol: 'sd', text: 'نه مهرباني' },
  { language: 'Sinhala', symbol: 'si', text: 'නැ ස්තුතියි' },
  { language: 'Somali', symbol: 'so', text: 'Maya mahadsanid' },
  { language: 'Sundanese', symbol: 'su', text: 'henteu nuhun' },
  { language: 'Swahili', symbol: 'sw', text: 'hapana asante' },
  { language: 'Uzbek', symbol: 'uz', text: "yo'q, rahmat" },
  { language: 'Welsh', symbol: 'cy', text: 'Dim Diolch' },
  { language: 'Xhosa', symbol: 'xh', text: 'hayi enkosi' },
  { language: 'Yiddish', symbol: 'yi', text: 'ניין א דאנק' },
  { language: 'Yoruba', symbol: 'yo', text: 'rara o se' },
  { language: 'Zulu', symbol: 'zu', text: 'cha ngiyabonga' },
];
