// We're just treeting this like a giant JSON file but in TS
/* eslint-disable import/no-anonymous-default-export, import/no-default-export */
export default [
  { language: 'Zulu', symbol: 'zu', text: 'ngiyabonga' },
  { language: 'Yoruba', symbol: 'yo', text: 'o ṣeun' },
  { language: 'Yiddish', symbol: 'yi', text: 'דאַנקען' },
  { language: 'Xhosa', symbol: 'xh', text: 'enkosi' },
  { language: 'Welsh', symbol: 'cy', text: 'diolch' },
  { language: 'Uzbek', symbol: 'uz', text: 'rahmat' },
  { language: 'Swahili', symbol: 'sw', text: 'asante' },
  { language: 'Sundanese', symbol: 'su', text: 'hatur nuhun' },
  { language: 'Somali', symbol: 'so', text: 'mahadsanid' },
  { language: 'Sinhala', symbol: 'si', text: 'ස්තූතියි' },
  { language: 'Sindhi', symbol: 'sd', text: 'مهرباني' },
  { language: 'Shona', symbol: 'sn', text: 'ndatenda' },
  { language: 'Sesotho', symbol: 'st', text: 'kea leboha' },
  { language: 'Scots Gaelic', symbol: 'gd', text: 'mòran taing' },
  { language: 'Samoan', symbol: 'sm', text: 'faʻafetai' },
  { language: 'Ridanese', symbol: 'ri', text: '162811765686665220' },
  { language: 'Persian', symbol: 'fa', text: 'با تشکر' },
  { language: 'Pashto', symbol: 'ps', text: 'مننه' },
  { language: 'Nepali', symbol: 'ne', text: 'धन्यवाद' },
  { language: 'Myanmar', symbol: 'my', text: 'ကျေးဇူးတင်ပါတယ်' },
  { language: 'Mongolian', symbol: 'mn', text: 'баярлалаа' },
  { language: 'Maori', symbol: 'mi', text: 'whakawhetai' },
  { language: 'Maltese', symbol: 'mt', text: 'grazzi' },
  { language: 'Malagasy', symbol: 'mg', text: 'Misaotra' },
  { language: 'Macedonian', symbol: 'mk', text: 'благодарам' },
  { language: 'Luxembourgish', symbol: 'lb', text: 'Merci' },
  { language: 'Latin', symbol: 'la', text: 'gratias ago' },
  { language: 'Lao', symbol: 'lo', text: 'ຂອບໃຈ' },
  { language: 'Kyrgyz', symbol: 'ky', text: 'рахмат' },
  { language: 'Khmer', symbol: 'km', text: 'សូមអរគុណ' },
  { language: 'Kazakh', symbol: 'kk', text: 'рахмет' },
  { language: 'Kannada', symbol: 'kn', text: 'ಧನ್ಯವಾದಗಳು' },
  { language: 'Javanese', symbol: 'jw', text: 'matur nuwun' },
  { language: 'Irish', symbol: 'ga', text: 'go raibh maith agat' },
  { language: 'Igbo', symbol: 'ig', text: 'daalụ' },
  { language: 'Icelandic', symbol: 'is', text: 'takk fyrir' },
  { language: 'Hungarian', symbol: 'hu', text: 'Kösz' },
  { language: 'Hmong', symbol: 'hmn', text: 'ua tsaug' },
  { language: 'Hindi', symbol: 'hi', text: 'धन्यवाद' },
  { language: 'Hawaiian', symbol: 'haw', text: 'mahalo' },
  { language: 'Hausa', symbol: 'ha', text: 'godiya' },
  { language: 'Haitian Creole', symbol: 'ht', text: 'mèsi' },
  { language: 'Gujarati', symbol: 'gu', text: 'આભાર' },
  { language: 'Georgian', symbol: 'ka', text: 'მადლობა' },
  { language: 'Galician', symbol: 'gl', text: 'grazas' },
  { language: 'Frisian', symbol: 'fy', text: 'tank' },
  { language: 'Corsican', symbol: 'co', text: 'Grazie' },
  { language: 'Chichewa', symbol: 'ny', text: 'zikomo' },
  { language: 'Cebuano', symbol: 'ceb', text: 'salamat' },
  { language: 'Bosnian', symbol: 'bs', text: 'hvala' },
  { language: 'Belarusian', symbol: 'be', text: 'дзякуй' },
  { language: 'Basque', symbol: 'eu', text: 'eskerrik asko' },
  { language: 'Azerbaijani', symbol: 'az', text: 'təşəkkürlər' },
  { language: 'Armenian', symbol: 'hy', text: 'շնորհակալություն' },
  { language: 'Amharic', symbol: 'am', text: 'አመሰግናለሁ' },
  { language: 'Albanian', symbol: 'sq', text: 'Faleminderit' },
  { language: 'Afrikaans', symbol: 'af', text: 'dankie' },
  { language: 'Vietnamese', symbol: 'vi', text: 'cảm ơn' },
  { language: 'Urdu', symbol: 'ur', text: 'شکریہ' },
  { language: 'Ukrainian', symbol: 'uk', text: 'Дякую' },
  { language: 'Turkish', symbol: 'tr', text: 'Teşekkürler' },
  { language: 'Thai', symbol: 'th', text: 'ขอบคุณ' },
  { language: 'Telugu', symbol: 'te', text: 'ధన్యవాదాలు' },
  { language: 'Tamil', symbol: 'ta', text: 'நன்றி' },
  { language: 'Tajik', symbol: 'tg', text: 'ташаккур' },
  { language: 'Swedish', symbol: 'sv', text: 'tack' },
  { language: 'Slovenian', symbol: 'sl', text: 'hvala' },
  { language: 'Slovak', symbol: 'sk', text: 'Vďaka' },
  { language: 'Serbian', symbol: 'sr', text: 'Хвала' },
  { language: 'Romanian', symbol: 'ro', text: 'Mulțumiri' },
  { language: 'Portuguese', symbol: 'pt', text: 'obrigado' },
  { language: 'Polish', symbol: 'pl', text: 'dzięki' },
  { language: 'Norwegian', symbol: 'no', text: 'Takk' },
  { language: 'Marathi', symbol: 'mr', text: 'धन्यवाद' },
  { language: 'Malayalam', symbol: 'ml', text: 'നന്ദി' },
  { language: 'Malay', symbol: 'ms', text: 'terima kasih' },
  { language: 'Lithuanian', symbol: 'lt', text: 'dėkoju' },
  { language: 'Latvian', symbol: 'lv', text: 'Paldies' },
  { language: 'Korean', symbol: 'ko', text: '감사' },
  { language: 'Indonesian', symbol: 'id', text: 'Terima kasih' },
  { language: 'Hebrew', symbol: 'iw', text: 'תודה' },
  { language: 'Greek', symbol: 'el', text: 'ευχαριστώ' },
  { language: 'Finnish', symbol: 'fi', text: 'Kiitos' },
  { language: 'Filipino', symbol: 'tl', text: 'salamat' },
  { language: 'Estonian', symbol: 'et', text: 'aitäh' },
  { language: 'Esperanto', symbol: 'eo', text: 'Dankon' },
  { language: 'Danish', symbol: 'da', text: 'tak' },
  { language: 'Czech', symbol: 'cs', text: 'dík' },
  { language: 'Croatian', symbol: 'hr', text: 'Hvala' },
  { language: 'Chinese Traditional', symbol: 'zh-tw', text: '謝謝' },
  { language: 'Chinese Simplified', symbol: 'zh-cn', text: '谢谢' },
  { language: 'Catalan', symbol: 'ca', text: 'gràcies' },
  { language: 'Bulgarian', symbol: 'bg', text: 'Благодаря' },
  { language: 'Bengali', symbol: 'bn', text: 'ধন্যবাদ' },
  { language: 'Spanish', symbol: 'es', text: 'Gracias' },
  { language: 'Russian', symbol: 'ru', text: 'Спасибо' },
  { language: 'Japanese', symbol: 'ja', text: 'ありがとう' },
  { language: 'Italian', symbol: 'it', text: 'Grazie' },
  { language: 'German', symbol: 'de', text: 'Vielen Dank' },
  { language: 'French', symbol: 'fr', text: 'Merci' },
  { language: 'Dutch', symbol: 'nl', text: 'bedankt' },
  { language: 'Arabic', symbol: 'ar', text: 'شكر' },
];
